### ISSUE TITLE
Request to add more stations

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/dms_datastore#11]
### Description

Some stations available on CDEC are missing. Please add these
I have checked them against the existing data store and I don't find them there. 
Some are CDEC calculations so we might need to show them as CDEC agency alone. 

[all_missing_cleaned.csv](https://github.com/CADWRDeltaModeling/dms_datastore/files/13243799/all_missing_cleaned.csv)

`,Station,ID,Elev (feet),Latitude,Longitude,County,River Basin,geometry
0,DELTA RUNOFF ONE DAY CALCULATION,DRO,6,38.042,-121.642,CONTRA COSTA,DELTA,POINT (-121.642 38.042)
1,COSUMNES RIVER NEAR MCCONNELL,MCC,5,38.357666,-121.343735,SACRAMENTO,COSUMNES R,POINT (-121.343735 38.357666)
2,GEORGIANA SLOUGH AT MOKELUMNE R,GSM,18,38.129533,-121.582974,SACRAMENTO,MOKELUMNE R,POINT (-121.582974 38.129533)
3,MOKELUMNE RIVER AT WOODBRIDGE,WBR,46,38.159,-121.302,SAN JOAQUIN,MOKELUMNE R,POINT (-121.302 38.159)
4,SACRAMENTO R AT WALNUT GROVE STAGE,WGS,22,38.239414,-121.51672,SACRAMENTO,SACRAMENTO R,POINT (-121.51672 38.239414)
5,SAN JOAQUIN R AT RINDGE PUMP,RGP,10,37.997279,-121.419451,SAN JOAQUIN,SAN JOAQUIN R,POINT (-121.419451 37.997279)
6,STOCKTON DEEP WATER SHIP CHANNEL DO,SDO,15,37.963,-121.365,SAN JOAQUIN,SAN JOAQUIN R,POINT (-121.365 37.963)
7,AMERICAN RIVER BELOW WATT AVE BRIDGE,AWB,50,38.567,-121.387,SACRAMENTO,AMERICAN R,POINT (-121.387 38.567)
8,BRYTE LAB,BYL,25,38.600098,-121.539543,YOLO,SACRAMENTO R,POINT (-121.539543 38.600098)
9,COLUSA BASIN DRAIN AT KNIGHTS LANDING,KLG,0,38.79947,-121.725203,SUTTER,SACRAMENTO R,POINT (-121.725203 38.79947)
10,BYRON BETHANY IRRIGATION DIST DIVERSION,BBI,3,37.8298,-121.5574,CONTRA COSTA,DELTA,POINT (-121.5574 37.8298)
11,CCWD MIDDLE RIVER PP ON VICTORIA CANAL,CCW,0,37.86654,-121.54379,CONTRA COSTA,DELTA,POINT (-121.54379 37.86654)
12,EAST CONTRA COUNTY ID PP#1,ECD,22,37.917863,-121.625999,CONTRA COSTA,DELTA,POINT (-121.625999 37.917863)
13,OLD & MIDDLE RVRS TIDALLY FILTERED EST,OMR,10,37.97,-121.5711,SAN JOAQUIN,DELTA,POINT (-121.5711 37.97)
14,SAN JOAQUIN R AT MAZE RD BRIDGE,MRB,39,37.6414,-121.2276,STANISLAUS,SAN JOAQUIN R,POINT (-121.2276 37.6414)
15,DISCOVERY BAY AT DISCOVERY BAY BLVD,DBD,9,37.8928,-121.6025,CONTRA COSTA,SAN JOAQUIN R,POINT (-121.6025 37.8928)
16,DRAINAGE AT ARBOR ROAD,DAR,20,37.768959,-121.419414,SAN JOAQUIN,SAN JOAQUIN R,POINT (-121.419414 37.768959)
17,JONES TRACT,JTR,-19,37.9224,-121.5182,SAN JOAQUIN,DELTA,POINT (-121.5182 37.9224)
18,PARADISE CUT ABV OLD R,PCO,26,37.801944,-121.412306,SAN JOAQUIN,DELTA,POINT (-121.412306 37.801944)
19,CORDELIA PUMPING PLANT (KG002111),CPP,2,38.2276,-122.1347,SOLANO,DELTA,POINT (-122.1347 38.2276)
20,DELTA OUTFLOW,DTO,0,38.059,-122.025,SOLANO,DELTA,POINT (-122.025 38.059)
21,PELICAN POINT AT ROARING RIVER,PEL,0,38.110869,-121.9718,SOLANO,DELTA,POINT (-121.9718 38.110869)
22,ROARING RIVER,ROR,10,38.092,-121.889,SOLANO,DELTA,POINT (-121.889 38.092)
23,TEAL CLUB AT FRANK HORAN SLOUGH,TEA,0,38.1766,-122.0872,SOLANO,DELTA,POINT (-122.0872 38.1766)
`

**Comment by water-e** [comment]
OK let's talk when I'm back.

**Comment by water-e** [comment]
Responses by data stream. Some are feasible, some are already there, a couple are odd ones I'd rather omit and some of the computed are daily.

0,DELTA RUNOFF ONE DAY CALCULATION,DRO
Is this used by anyone? Fine with adding anything needed and understood. There is another set of stations for atmospheric we can incorporate if we can standardize the data.

1,COSUMNES RIVER NEAR MCCONNELL,MCC
Not representative of Delta conditions AFAIK, consult Lily as to need. 

2,GEORGIANA SLOUGH AT MOKELUMNE R,GSM,18,38.129533,-121.582974,SACRAMENTO,MOKELUMNE R,POINT (-121.582974 38.129533) 
Already in repo, 40 year history of elev

3,MOKELUMNE RIVER AT WOODBRIDGE,WBR,46,38.159,-121.302,SAN JOAQUIN,MOKELUMNE R,POINT (-121.302 38.159) 
Daily for flow, which is to be addressed elsewhere. This is a BC for models, so downloaded for SCHISM and DSM2 often. However the stage on CDEC isn't something we'd be able to interpret

4,SACRAMENTO R AT WALNUT GROVE STAGE,WGS,22,38.239414,-121.51672,SACRAMENTO,SACRAMENTO R,POINT (-121.51672 38.239414) 
Will add

5,SAN JOAQUIN R AT RINDGE PUMP,RGP,10,37.997279,-121.419451,SAN JOAQUIN,SAN JOAQUIN R,POINT (-121.419451 37.997279) 
Already in database and repo under the name "rindg". This was in WDL but not CDEC for a long time, so we rolled our own id. 
Ideally we'd change, though it is a certain amount of work.

6,STOCKTON DEEP WATER SHIP CHANNEL DO,SDO,15,37.963,-121.365,SAN JOAQUIN,SAN JOAQUIN R,POINT (-121.365 37.963)
This is the DISE stockton station. I think we can add
 
7,AMERICAN RIVER BELOW WATT AVE BRIDGE,AWB,50,38.567,-121.387,SACRAMENTO,AMERICAN R,POINT (-121.387 38.567) 
Already in repo with 2007-2023 history. USGS.

8,BRYTE LAB,BYL,25,38.600098,-121.539543,YOLO,SACRAMENTO R,POINT (-121.539543 38.600098)
Unreliable.
 
9,COLUSA BASIN DRAIN AT KNIGHTS LANDING,KLG,0,38.79947,-121.725203,SUTTER,SACRAMENTO R,POINT (-121.725203 38.79947) 
Amenable, but don't know how to interpret. Which variables? gates?

10,BYRON BETHANY IRRIGATION DIST DIVERSION,BBI,3,37.8298,-121.5574,CONTRA COSTA,DELTA,POINT (-121.5574 37.8298) 
Daily.

11,CCWD MIDDLE RIVER PP ON VICTORIA CANAL,CCW,0,37.86654,-121.54379,CONTRA COSTA,DELTA,POINT (-121.54379 37.86654) 
Daily

12,EAST CONTRA COUNTY ID PP#1,ECD,22,37.917863,-121.625999,CONTRA COSTA,DELTA,POINT (-121.625999 37.917863) 
Don't know how to interpret. Out of scope?

13,OLD & MIDDLE RVRS TIDALLY FILTERED EST,OMR,10,37.97,-121.5711,SAN JOAQUIN,DELTA,POINT (-121.5711 37.97) 
Daily. When we get there will add under auspices of Dayflow for long term and O&M for realtime.

14,SAN JOAQUIN R AT MAZE RD BRIDGE,MRB,39,37.6414,-121.2276,STANISLAUS,SAN JOAQUIN R,POINT (-121.2276 37.6414) 
Will add, though not high priority if it is hard.

15,DISCOVERY BAY AT DISCOVERY BAY BLVD,DBD,9,37.8928,-121.6025,CONTRA COSTA,SAN JOAQUIN R,POINT (-121.6025 37.8928) 
Already in repo for EC and temp. Currently some communications going on about the flow part. NCRO needs to add this to their 
nightly dump.

16,DRAINAGE AT ARBOR ROAD,DAR,20,37.768959,-121.419414,SAN JOAQUIN,SAN JOAQUIN R,POINT (-121.419414 37.768959) 
Already in repo 

17,JONES TRACT,JTR,-19,37.9224,-121.5182,SAN JOAQUIN,DELTA,POINT (-121.5182 37.9224) 
This station is just detritis. Deliberately omitted.

18,PARADISE CUT ABV OLD R,PCO,26,37.801944,-121.412306,SAN JOAQUIN,DELTA,POINT (-121.412306 37.801944)
This sttion is NCRO. It is in the dbase but commented. Will try uncommenting.
 
19,CORDELIA PUMPING PLANT (KG002111),CPP,2,38.2276,-122.1347,SOLANO,DELTA,POINT (-122.1347 38.2276)
Urban setting, not sure this is in scope.
 
20,DELTA OUTFLOW,DTO,0,38.059,-122.025,SOLANO,DELTA,POINT (-122.025 38.059) 
Daily. When we get to daily, intent to add under auspices of Dayflow for long term and O&M for realtime.

21,PELICAN POINT AT ROARING RIVER,PEL,0,38.110869,-121.9718,SOLANO,DELTA,POINT (-121.9718 38.110869) 
Amenable, but this isn't a tidally-connected station and won't know how to QA/QC. Do we have plans for it?

22,ROARING RIVER,ROR,10,38.092,-121.889,SOLANO,DELTA,POINT (-121.889 38.092) 
Amenable, but this isn't a tidally-connected station and won't know how to QA/QC. Do we have plans for it?

23,TEAL CLUB AT FRANK HORAN SLOUGH,TEA,0,38.1766,-122.0872,SOLANO,DELTA,POINT (-122.0872 38.1766) 
In the database and repo, but also this is a discontinued station and has been since 2021.

**Comment by dwr-psandhu** [comment]
Thanks for the explanation. I don't see the need for any other stations for now. Closing issue
