### ISSUE TITLE
ERROR: No matching distribution found for beautifulsoup4

### ISSUE THREAD

**Issue by HansKimDWR** [CADWRDeltaModeling/dms_datastore#24]
* schimpy version:
* Python version: 3.11
* Operating System: Windows

### Description

"No matching distribution found for beautifulsoup4" error is encountered during installation.

### What I Did

With `pip install -e .`, following error is encountered:

![image](https://github.com/CADWRDeltaModeling/dms_datastore/assets/57460514/eaae25e3-f578-4a10-b79e-dd0703018ac0)

The conda environment has vtools3 installed, with python=3.11:

![image](https://github.com/CADWRDeltaModeling/dms_datastore/assets/57460514/cbf321ac-e1e4-41f6-9502-80cee0c58442)

**Comment by water-e** [comment]
I think we need a simpler issue. This mix of pip and conda, which may be due to not using --no-deps, is too complicated to debug. What toolset are tyou trying to use.? If it is for SCHISM please use the recommended environment schism_env.yml on BayDeltaSCHISM and make sure channel priorities are set in your conda environment. You can pip install -e . after that and it will work fine. If it is just for dms_datastore we can debug from there.

**Comment by HansKimDWR** [comment]
@water-e I was attempting to create an environment for schimpy from scratch. I tried the approaches you suggested (installing with '--no-deps' and first creating an environment with schism_env.yml) separately, and they worked; dms-datastore was installed successfully.

@kjnam @dwr-psandhu Seeing I am able to install dms-datastore successfully, I did not test for SSL issue on my personal PC. 

Closing the issue.
