### ISSUE TITLE
auto_screen is very verbose and takes many hours to run

### ISSUE THREAD

**Issue by dwr-psandhu** [CADWRDeltaModeling/dms_datastore#45]
auto screening prints out a lot to the console which makes it hard to use it. I suggest using logging and then controlling the amount of information being written to console.

It is also very slow, taking upto 18 hours to run. Not sure if this is because the algorithms are heavy or because of inefficient implentation.

**Comment by water-e** [comment]
I'm not sure very much of that is really helpful and much of it was development stuff. We can discuss the role of logging.
________________________________
From: Nicky Sandhu ***@***.***>
Sent: Wednesday, February 14, 2024 7:12 AM
To: CADWRDeltaModeling/dms_datastore ***@***.***>
Cc: Ateljevich, ***@***.*** ***@***.***>; Assign ***@***.***>
Subject: [CADWRDeltaModeling/dms_datastore] auto_screen is very verbose and takes many hours to run (Issue #45)


auto screening prints out a lot to the console which makes it hard to use it. I suggest using logging and then controlling the amount of information being written to console.

It is also very slow, taking upto 18 hours to run. Not sure if this is because the algorithms are heavy or because of inefficient implentation.

**Comment by dwr-psandhu** [comment]
Reran with the latest build of env. Still running at 6.5 hours. Did your version run any faster?

**Comment by water-e** [comment]
I'll launch it now. I got 1:12 for the population and 3.something hours for reformatting.
________________________________

**Comment by dwr-psandhu** [comment]
after relaunching it yesterday with a rebuilt environment with latest dependencies, the raw and formatted took 2 hours, however the auto screening took 17 hours.

**Comment by water-e** [comment]
The only thing I want to add about downloading is I don't think you should draw conclusions that seperate launches are faster than multithreads. It is very hard to tell 1 hour from 2 on the downloads. Reformatting should have a stable speed from invocation to invocation and I can break it up a little more, but that should only favor speed on my machine not on a 4 or 8 proc system – for it is a traditional scalar debugging job. It used to take 90 minutes I'm sure it can again.
________________________________
